//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsManager {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbMessage;
		
		protected System.Web.UI.HtmlControls.HtmlTable tbForm;
		
		protected System.Web.UI.WebControls.TextBox tbUsername;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox tbPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.Button btnOK1;
		
		protected System.Web.UI.WebControls.CheckBox CheckBox1;
		
		protected System.Web.UI.WebControls.HyperLink hkMenu;
	}
}
